[project]
name = "test-kernel"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "networking-python-sdk"
]

[tool.uv.sources]
networking-python-sdk = { path = "../python_sdk", editable = true }
