#!/home/henry/Desktop/shopping_cart/backend/venv/bin/python
# noinspection PyPep8
import json
import re
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path
import msgspec
import inspect
import shutil

sys.path.insert(1, str(Path(__file__).parent.parent.joinpath("backend").absolute()))
from server import server

npm_bin_dir = Path(__file__).parent.joinpath("node_modules/.bin")
sdk_file = "src/generated/sdk.ts"
with tempfile.NamedTemporaryFile("w") as f:
    x = server.openapi_schema.to_schema()
    f.write(json.dumps(server.openapi_schema.to_schema()))
    f.seek(0)
    f.flush()
    subprocess.run(
        f"{npm_bin_dir / 'oazapfts'} {f.name} {sdk_file} --optimistic",
        cwd=Path(__file__).parent,
        shell=True,
    )
with open(sdk_file, "r+") as f:
    content = f.read()
    f.seek(0, 0)
    f.write("/* eslint-disable */\n" + content)


import models

_models = [getattr(models, m) for m in dir(models)]
_models = [
    m
    for m in _models
    if inspect.isclass(m) and issubclass(m, msgspec.Struct) and m is not msgspec.Struct
]
_, _models = msgspec.json.schema_components(_models, ref_template="{name}.json")


type_dir = Path(__file__).parent / str(uuid.uuid4())
type_dir.mkdir(exist_ok=True)
for name, _model in _models.items():
    with open(type_dir / f"{name}.json", "w") as f:
        json.dump(_model, f)

model_ts = Path(__file__).parent / "src" / "generated" / "models.ts"
subprocess.run(
    f"{npm_bin_dir/'json2ts'} -i '{type_dir}/*.json' --additionalProperties=false > {model_ts}",
    cwd=type_dir,
    shell=True,
)
shutil.rmtree(type_dir)


def remove_redundant_interfaces(file_content: str):
    # Remove redundant interfaces and keep track of unique interface names
    unique_interfaces = {}
    interfaces = re.finditer(
        r"^export\s+interface\s+(\w+)\s*{\n.*?^}",
        file_content,
        flags=re.MULTILINE | re.DOTALL,
    )
    for intf in interfaces:
        unique_interfaces[intf.group(1)] = intf.group(0)
    header = """/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
 """
    return header + "\n" + "\n\n".join(unique_interfaces.values())


with open(model_ts, "r+") as f:
    file_content = f.read()
    f.seek(0)
    cleaned_content = remove_redundant_interfaces(file_content)
    f.write(cleaned_content)
    f.truncate()
