#!/usr/bin/env bash
set -e # Exit on first failure
cd "$(dirname "$0")" || exit 1

deb_file="required-debs.txt" # Newline seperated apt package names
pyreq_file="requirements.txt" # Standard requirements.txt


if [[ -f "$deb_file" ]] && [[ -f "$pyreq_file" ]]; then
  echo "Required files found"
else
  echo "Required files missing"
  exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "Python3 is not installed. Please install Python3."
    exit 1
fi
if [[ -e "venv" ]]; then
  sudo rm -rf venv
fi
python3 -m venv venv
venv/bin/pip install -r "$pyreq_file"

xargs sudo apt-get install < "$deb_file"

