// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: networking.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebrtcProxy_Connect_FullMethodName = "/networking.WebrtcProxy/Connect"
)

// WebrtcProxyClient is the client API for WebrtcProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebrtcProxyClient interface {
	// Streams all fields in `Mutation` and returns all fields in `Event`
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Mutation, Event], error)
}

type webrtcProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewWebrtcProxyClient(cc grpc.ClientConnInterface) WebrtcProxyClient {
	return &webrtcProxyClient{cc}
}

func (c *webrtcProxyClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Mutation, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WebrtcProxy_ServiceDesc.Streams[0], WebrtcProxy_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Mutation, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebrtcProxy_ConnectClient = grpc.BidiStreamingClient[Mutation, Event]

// WebrtcProxyServer is the server API for WebrtcProxy service.
// All implementations must embed UnimplementedWebrtcProxyServer
// for forward compatibility.
type WebrtcProxyServer interface {
	// Streams all fields in `Mutation` and returns all fields in `Event`
	Connect(grpc.BidiStreamingServer[Mutation, Event]) error
	mustEmbedUnimplementedWebrtcProxyServer()
}

// UnimplementedWebrtcProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebrtcProxyServer struct{}

func (UnimplementedWebrtcProxyServer) Connect(grpc.BidiStreamingServer[Mutation, Event]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWebrtcProxyServer) mustEmbedUnimplementedWebrtcProxyServer() {}
func (UnimplementedWebrtcProxyServer) testEmbeddedByValue()                     {}

// UnsafeWebrtcProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebrtcProxyServer will
// result in compilation errors.
type UnsafeWebrtcProxyServer interface {
	mustEmbedUnimplementedWebrtcProxyServer()
}

func RegisterWebrtcProxyServer(s grpc.ServiceRegistrar, srv WebrtcProxyServer) {
	// If the following call pancis, it indicates UnimplementedWebrtcProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebrtcProxy_ServiceDesc, srv)
}

func _WebrtcProxy_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebrtcProxyServer).Connect(&grpc.GenericServerStream[Mutation, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebrtcProxy_ConnectServer = grpc.BidiStreamingServer[Mutation, Event]

// WebrtcProxy_ServiceDesc is the grpc.ServiceDesc for WebrtcProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebrtcProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "networking.WebrtcProxy",
	HandlerType: (*WebrtcProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _WebrtcProxy_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "networking.proto",
}
